# Generated by Django 2.1.3 on 2019-03-04 23:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_auto_20190304_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('dateSampled', models.DateTimeField(default=django.utils.timezone.now)),
                ('transNumber', models.IntegerField()),
                ('startLat', models.FloatField()),
                ('startLong', models.FloatField()),
                ('endLat', models.FloatField()),
                ('endLong', models.FloatField()),
                ('clams', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='clam',
            name='author',
        ),
        migrations.DeleteModel(
            name='Clam',
        ),
    ]
