# Generated by Django 2.1.3 on 2019-03-11 23:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190304_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='surveyName',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
