# Generated by Django 2.1.3 on 2019-03-13 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_survey_surveyname'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='beaches',
            field=models.CharField(choices=[('pismo', 'Pismo Beach'), ('morro', 'Morro Bay'), ('cayucos', 'Cayucos Beach'), ('oceano', 'Oceano Beach'), ('coronado', 'Coronado Beach'), ('zuma', 'Zuma Beach'), ('huntington', 'Huntington Beach'), ('imperial', 'Imperial Beach'), ('moonlight', 'Moonlight Beach'), ('siverStrand', 'Siver Strand Beach'), ('santaMonica', 'Santa Monica Beach'), ('avila', 'Avila Beach'), ('pointMugu', 'point Mugu Beach')], default='pismo', max_length=100),
        ),
    ]
