# Generated by Django 2.1.3 on 2019-03-13 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_survey_beaches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='beaches',
            field=models.CharField(max_length=100),
        ),
    ]
