# Generated by Django 2.1.3 on 2019-03-13 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190312_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='airTemp',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='waterTemp',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
