# Generated by Django 2.1.3 on 2019-03-13 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_survey_beaches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='clams',
            field=models.CharField(max_length=5000),
        ),
    ]
